server:
  undertow:
    io-threads: 4
    worker-threads: 128
    buffer-size: 1024
    direct-buffers: true
#    buffers-per-region: 1024
  servlet:
    context-path: /channel
  port: 8890
spring:
  profiles:
    active: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: @datasource.url@
      username: @datasource.username@
      password: @datasource.password@
      initial-size: @datasource.initial-size@
      max-active: @datasource.max-active@
      min-evictable-idle-time-millis: 100000
      validation-query: select 1
  redis:
    database: 0
    host: @redis.ip@
    port: 6379
    password: @redis.password@
    jedis:
      pool:
        #最大连接数
        max-active: @redis.max-active@
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: @redis.max-idle@
        #最小空闲
        min-idle: @redis.min-idle@
#  rabbitmq:
#    host: @rabbitmq.ip@
#    port: 5672
#    username: @rabbitmq.username@
#    password: @rabbitmq.password@
#    virtual-host: /
#    publisher-confirms: true    # 开启发送确认
#    publisher-returns:  true    # 开启发送失败退回
#    listener:
#      direct:
#        acknowledge-mode: manual
#      simple:
#        acknowledge-mode: manual
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

#MyBatis配置
mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#Mapper通用插件
mapper:
  mappers: com.MyMapper
  not-empty: false
  identity: MYSQL

#日志
logging:
#  pattern:
#    console: "%d - %msg%n"
  file: ./log/cutomize.log
  level:
    com.mapper: debug


