server:
  undertow:
    io-threads: 4
    worker-threads: 128
    buffer-size: 1024
    direct-buffers: true
  servlet:
    context-path: /channel
  port: 8890
spring:
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: @datasource.url@
      username: @datasource.username@
      password: @datasource.password@
      initial-size: @datasource.initial-size@
      max-active: @datasource.max-active@
      min-evictable-idle-time-millis: 100000
      validation-query: select 1

    #dnsMonitoring: false

#  rabbitmq:
#    host: @rabbitmq.ip@
#    port: 5672
#    username: @rabbitmq.username@
#    password: @rabbitmq.password@
#    virtual-host: /
#    publisher-confirms: true    # 开启发送确认
#    publisher-returns:  true    # 开启发送失败退回
#    listener:
#      direct:
#        acknowledge-mode: manual
#      simple:
#        acknowledge-mode: manual
#MyBatis配置
mybatis:
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#Mapper通用插件
mapper:
  mappers: com.MyMapper
  not-empty: false
  identity: MYSQL

#日志
logging:
  config: classpath:log4j2.xml

